/**
 * v8.1: painted icon + sprite manifests (AUTO-GENERATED from the Grok
 * total-art run). Consumers fall back to emoji when an entry is missing.
 */
export const ICON_ART: Record<string, string> = {
  barrel: 'art/icons/barrel.png',
  boss: 'art/icons/boss.png',
  breeding: 'art/icons/breeding.png',
  character: 'art/icons/character.png',
  chest: 'art/icons/chest.png',
  chronicle: 'art/icons/chronicle.png',
  crown: 'art/icons/crown.png',
  deck: 'art/icons/deck.png',
  door: 'art/icons/door.png',
  sort_source: 'art/icons/sort_source.png',
  sort_name: 'art/icons/sort_name.png',
  sort_cost: 'art/icons/sort_cost.png',
  sort_type: 'art/icons/sort_type.png',
  sort_rarity: 'art/icons/sort_rarity.png',
  sort_count: 'art/icons/sort_count.png',
  sort_reverse: 'art/icons/sort_reverse.png',
  equipment: 'art/icons/equipment.png',
  event: 'art/icons/event.png',
  event_mossyIdol: 'art/icons/event_mossyIdol.png',
  event_gamblersGhost: 'art/icons/event_gamblersGhost.png',
  event_widowsLoom: 'art/icons/event_widowsLoom.png',
  event_bubblingSpring: 'art/icons/event_bubblingSpring.png',
  event_wanderingPeddler: 'art/icons/event_wanderingPeddler.png',
  event_collapsedTamer: 'art/icons/event_collapsedTamer.png',
  event_singingBones: 'art/icons/event_singingBones.png',
  event_humingHive: 'art/icons/event_humingHive.png',
  event_crackedWardstone: 'art/icons/event_crackedWardstone.png',
  event_abandonedCamp: 'art/icons/event_abandonedCamp.png',
  event_mirrorPool: 'art/icons/event_mirrorPool.png',
  event_tollTroll: 'art/icons/event_tollTroll.png',
  event_fallenStar: 'art/icons/event_fallenStar.png',
  event_weepingLady: 'art/icons/event_weepingLady.png',
  event_rustedVault: 'art/icons/event_rustedVault.png',
  event_faerieRing: 'art/icons/event_faerieRing.png',
  event_oldBell: 'art/icons/event_oldBell.png',
  event_gutteringBonfire: 'art/icons/event_gutteringBonfire.png',
  event_patientChest: 'art/icons/event_patientChest.png',
  event_lostPilgrim: 'art/icons/event_lostPilgrim.png',
  event_namelessGrave: 'art/icons/event_namelessGrave.png',
  event_wagerOfFingers: 'art/icons/event_wagerOfFingers.png',
  event_lowDoorWarden: 'art/icons/event_lowDoorWarden.png',
  event_ashfall: 'art/icons/event_ashfall.png',
  event_woundedAlpha: 'art/icons/event_woundedAlpha.png',
  event_threeDeserters: 'art/icons/event_threeDeserters.png',
  event_waxEffigy: 'art/icons/event_waxEffigy.png',
  event_lanternBearer: 'art/icons/event_lanternBearer.png',
  event_thirstyAltar: 'art/icons/event_thirstyAltar.png',
  event_quietChapel: 'art/icons/event_quietChapel.png',
  event_drownedCoffer: 'art/icons/event_drownedCoffer.png',
  event_courtOfCrows: 'art/icons/event_courtOfCrows.png',
  event_brokenWard: 'art/icons/event_brokenWard.png',
  event_kneelingKnight: 'art/icons/event_kneelingKnight.png',
  event_weighingStone: 'art/icons/event_weighingStone.png',
  event_sleeplessMiller: 'art/icons/event_sleeplessMiller.png',
  event_orphanedTorch: 'art/icons/event_orphanedTorch.png',
  event_beastInWall: 'art/icons/event_beastInWall.png',
  event_coinlessFerryman: 'art/icons/event_coinlessFerryman.png',
  event_starvingShrine: 'art/icons/event_starvingShrine.png',
  event_moltingColossus: 'art/icons/event_moltingColossus.png',
  family_slime: 'art/icons/family_slime.png',
  family_dragon: 'art/icons/family_dragon.png',
  family_beast: 'art/icons/family_beast.png',
  family_bird: 'art/icons/family_bird.png',
  family_plant: 'art/icons/family_plant.png',
  family_bug: 'art/icons/family_bug.png',
  family_devil: 'art/icons/family_devil.png',
  family_undead: 'art/icons/family_undead.png',
  family_material: 'art/icons/family_material.png',
  gate_verdant: 'art/icons/gate_verdant.png',
  gate_hollow: 'art/icons/gate_hollow.png',
  gate_sunken: 'art/icons/gate_sunken.png',
  gate_storm: 'art/icons/gate_storm.png',
  gate_abyss: 'art/icons/gate_abyss.png',
  gates: 'art/icons/gates.png',
  gearshop: 'art/icons/gearshop.png',
  gold: 'art/icons/gold.png',
  herb: 'art/icons/herb.png',
  item_herb: 'art/icons/herb.png',
  item_potion: 'art/icons/item_potion.png',
  item_elixir: 'art/icons/item_elixir.png',
  item_water: 'art/icons/item_water.png',
  item_ether: 'art/icons/item_ether.png',
  item_jerky: 'art/icons/item_jerky.png',
  item_sirloin: 'art/icons/item_sirloin.png',
  item_primesteak: 'art/icons/item_primesteak.png',
  item_witchwick: 'art/icons/item_waybrand.png', // pre-rename art; still the lantern-coal painting, not yet a candle
  itemshop: 'art/icons/itemshop.png',
  merchant: 'art/icons/merchant.png',
  quests: 'art/icons/quests.png',
  rest: 'art/icons/rest.png',
  save: 'art/icons/save.png',
  secret: 'art/icons/secret.png',
  shrine: 'art/icons/shrine.png',
  smith: 'art/icons/smith.png',
  stable: 'art/icons/stable.png',
  stairs: 'art/icons/stairs.png',
  tavern: 'art/icons/tavern.png',
  vigor: 'art/icons/vigor.png',
  ward: 'art/icons/ward.png',
  waterpool: 'art/icons/waterpool.png',
  debris: 'art/icons/debris.png',
  archway: 'art/icons/archway.png',
};

export const SPRITE_ART: Record<string, string> = {
  merchant: 'art/sprites/merchant.png',
  player: 'art/sprites/player.png',
  tamer: 'art/sprites/tamer.png',
};

/** Per-gate ground/wall textures for continuous map terrain. */
export const TILE_TEXTURES: Record<string, { ground: string; wall: string }> = {
  verdant: { ground: 'art/tiles/verdant_ground.jpg', wall: 'art/tiles/verdant_wall.jpg' },
  hollow: { ground: 'art/tiles/hollow_ground.jpg', wall: 'art/tiles/hollow_wall.jpg' },
  sunken: { ground: 'art/tiles/sunken_ground.jpg', wall: 'art/tiles/sunken_wall.jpg' },
  storm: { ground: 'art/tiles/storm_ground.jpg', wall: 'art/tiles/storm_wall.jpg' },
  abyss: { ground: 'art/tiles/abyss_ground.jpg', wall: 'art/tiles/abyss_wall.jpg' },
};
