// AUTO-CURATED: Grok-painted character art (double QC'd). Missing ids fall back to procedural SVG.

export const PAINTED_MONSTERS: Record<string, string> = {
  adamantColossus: '/art/monsters/adamantColossus.jpg',
  archfiend: '/art/monsters/archfiend.jpg',
  behemoth: '/art/monsters/behemoth.jpg',
  boneshambler: '/art/monsters/boneshambler.jpg',
  bristleBoar: '/art/monsters/bristleBoar.jpg',
  bubblim: '/art/monsters/bubblim.jpg',
  cryptTyrant: '/art/monsters/cryptTyrant.jpg',
  dartWasp: '/art/monsters/dartWasp.jpg',
  drakeling: '/art/monsters/drakeling.jpg',
  duskFiend: '/art/monsters/duskFiend.jpg',
  elderTreant: '/art/monsters/elderTreant.jpg',
  emberwhelp: '/art/monsters/emberwhelp.jpg',
  fangPup: '/art/monsters/fangPup.jpg',
  frostWyrm: '/art/monsters/frostWyrm.jpg',
  gargoyle: '/art/monsters/gargoyle.jpg',
  gelKnight: '/art/monsters/gelKnight.jpg',
  gloomShroom: '/art/monsters/gloomShroom.jpg',
  goober: '/art/monsters/goober.jpg',
  grinGoblin: '/art/monsters/grinGoblin.jpg',
  grizzlord: '/art/monsters/grizzlord.jpg',
  hiveEmpress: '/art/monsters/hiveEmpress.jpg',
  impling: '/art/monsters/impling.jpg',
  infernoDragon: '/art/monsters/infernoDragon.jpg',
  lanternMoth: '/art/monsters/lanternMoth.jpg',
  lichAscendant: '/art/monsters/lichAscendant.jpg',
  livingArmor: '/art/monsters/livingArmor.jpg',
  mossOwl: '/art/monsters/mossOwl.jpg',
  nightTerror: '/art/monsters/nightTerror.jpg',
  onyxGolem: '/art/monsters/onyxGolem.jpg',
  pebblit: '/art/monsters/pebblit.jpg',
  peckerel: '/art/monsters/peckerel.jpg',
  phoenixling: '/art/monsters/phoenixling.jpg',
  razorMantis: '/art/monsters/razorMantis.jpg',
  shadowPanther: '/art/monsters/shadowPanther.jpg',
  shamblebones: '/art/monsters/shamblebones.jpg',
  shimmerOoze: '/art/monsters/shimmerOoze.jpg',
  skitterling: '/art/monsters/skitterling.jpg',
  skyTalon: '/art/monsters/skyTalon.jpg',
  sovereignSlime: '/art/monsters/sovereignSlime.jpg',
  sproutling: '/art/monsters/sproutling.jpg',
  stormDrake: '/art/monsters/stormDrake.jpg',
  stormRoc: '/art/monsters/stormRoc.jpg',
  thornVine: '/art/monsters/thornVine.jpg',
  wailingWisp: '/art/monsters/wailingWisp.jpg',
  yggdraBlossom: '/art/monsters/yggdraBlossom.jpg',
};

export const PAINTED_HEROES: Record<string, string> = {
  Bard: '/art/heroes/Bard.jpg',
  Knight: '/art/heroes/Knight.jpg',
  Mage: '/art/heroes/Mage.jpg',
  Thief: '/art/heroes/Thief.jpg',
  Warrior: '/art/heroes/Warrior.jpg',
};

export const PAINTED_NPCS: Record<string, string> = {
  bram: '/art/npcs/bram.jpg',
  casque: '/art/npcs/casque.jpg',
  dovey: '/art/npcs/dovey.jpg',
  fennick: '/art/npcs/fennick.jpg',
  kess: '/art/npcs/kess.jpg',
  maribel: '/art/npcs/maribel.jpg',
  ott: '/art/npcs/ott.jpg',
  rowan: '/art/npcs/rowan.jpg',
  sess: '/art/npcs/sess.jpg',
};
