// AUTO-CURATED: Grok-painted character art (transparent PNG). Missing ids fall back to SVG.

export const PAINTED_MONSTERS: Record<string, string> = {
  adamantColossus: 'art/monsters/adamantColossus.png',
  archfiend: 'art/monsters/archfiend.png',
  ashcrestVulture: 'art/monsters/ashcrestVulture.png',
  behemoth: 'art/monsters/behemoth.png',
  boneshambler: 'art/monsters/boneshambler.png',
  bristleBoar: 'art/monsters/bristleBoar.png',
  bubblim: 'art/monsters/bubblim.png',
  cinderScorpion: 'art/monsters/cinderScorpion.png',
  cryptTyrant: 'art/monsters/cryptTyrant.png',
  dartWasp: 'art/monsters/dartWasp.png',
  drakeling: 'art/monsters/drakeling.png',
  duskFiend: 'art/monsters/duskFiend.png',
  duskhound: 'art/monsters/duskhound.png',
  elderTreant: 'art/monsters/elderTreant.png',
  emberwhelp: 'art/monsters/emberwhelp.png',
  fangPup: 'art/monsters/fangPup.png',
  frostWyrm: 'art/monsters/frostWyrm.png',
  gargoyle: 'art/monsters/gargoyle.png',
  gelKnight: 'art/monsters/gelKnight.png',
  gloomShroom: 'art/monsters/gloomShroom.png',
  goober: 'art/monsters/goober.png',
  grinGoblin: 'art/monsters/grinGoblin.png',
  grizzlord: 'art/monsters/grizzlord.png',
  hiveEmpress: 'art/monsters/hiveEmpress.png',
  hollowMarionette: 'art/monsters/hollowMarionette.png',
  impling: 'art/monsters/impling.png',
  infernoDragon: 'art/monsters/infernoDragon.png',
  lanternMoth: 'art/monsters/lanternMoth.png',
  lichAscendant: 'art/monsters/lichAscendant.png',
  livingArmor: 'art/monsters/livingArmor.png',
  mossOwl: 'art/monsters/mossOwl.png',
  nightTerror: 'art/monsters/nightTerror.png',
  obsidianWarden: 'art/monsters/obsidianWarden.png',
  onyxGolem: 'art/monsters/onyxGolem.png',
  pebblit: 'art/monsters/pebblit.png',
  peckerel: 'art/monsters/peckerel.png',
  phoenixling: 'art/monsters/phoenixling.png',
  razorMantis: 'art/monsters/razorMantis.png',
  shadowPanther: 'art/monsters/shadowPanther.png',
  shamblebones: 'art/monsters/shamblebones.png',
  shimmerOoze: 'art/monsters/shimmerOoze.png',
  skitterling: 'art/monsters/skitterling.png',
  skyTalon: 'art/monsters/skyTalon.png',
  sovereignSlime: 'art/monsters/sovereignSlime.png',
  sproutling: 'art/monsters/sproutling.png',
  stormDrake: 'art/monsters/stormDrake.png',
  stormRoc: 'art/monsters/stormRoc.png',
  thornVine: 'art/monsters/thornVine.png',
  wailingWisp: 'art/monsters/wailingWisp.png',
  widowsBloom: 'art/monsters/widowsBloom.png',
  yggdraBlossom: 'art/monsters/yggdraBlossom.png',
};

export const PAINTED_HEROES: Record<string, string> = {
  Bard: 'art/heroes/Bard.png',
  Knight: 'art/heroes/Knight.png',
  Mage: 'art/heroes/Mage.png',
  Thief: 'art/heroes/Thief.png',
  Warrior: 'art/heroes/Warrior.png',
};

export const PAINTED_NPCS: Record<string, string> = {
  bram: 'art/npcs/bram.jpg',
  casque: 'art/npcs/casque.jpg',
  dovey: 'art/npcs/dovey.jpg',
  fennick: 'art/npcs/fennick.jpg',
  kess: 'art/npcs/kess.jpg',
  maribel: 'art/npcs/maribel.jpg',
  ott: 'art/npcs/ott.jpg',
  rowan: 'art/npcs/rowan.jpg',
  sess: 'art/npcs/sess.jpg',
};
