// =========================================================================
// THE BRIDGE — game state in, `Scene` out.
//
// This is the ONLY file in the project that knows about both worlds, and that
// is precisely why it exists. ENGINE_PLAN §2 rule 1:
//
//   "`lantern/` never imports from `engine/` or `components/`. It takes a
//    Scene and draws it. It does not know what a monster is."
//
// A renderer that reached into `engine/` would be untestable headless and
// unportable to the next game; a game that reached into `lantern/` would have
// its rules shaped by a projection. So the coupling gets a room of its own,
// and the whole of it is a PURE FUNCTION — an `Expedition` and a `Character`
// in, sprite lists and lights out. No GL, no DOM, no React, no clock but the
// `time` it is handed.
//
// TWO THINGS THAT ARE DELIBERATE AND EASY TO UNDO BY ACCIDENT:
//
// 1. THE SETS. `isRevealed` / `isOpened` / `isBroken` are `Array.includes`
//    over floor-scoped string keys (`floors.ts:135-145`). At DOM render rates
//    — a handful of renders per move — ~250 linear scans is invisible. At 60
//    fps it is the frame budget, and ENGINE_PLAN §8 item 6 calls it out by
//    name. `snapshotFloor` converts them ONCE per state change, into bare
//    "x,y" keys with the floor prefix already stripped, and every hot loop
//    below reads a `Set`. `floors.ts` is not touched: its signatures are the
//    game's, and this is a rendering concern.
//
// 2. THE FOG IS BLACK GEOMETRY, not an absent draw. An unrevealed tile gets an
//    opaque black quad rather than simply being skipped, because the board is
//    a physical slab (`board.ts`) and skipping the tile would show the FRAME's
//    timber through the hole. ENGINE_PLAN §14.1: fog of war is a physical
//    fact, not a UI convention — so the unexplored board is present, and dark.
// =========================================================================

import type { Character } from '../engine/entities/Character';
import type { FloorUnit, Expedition } from '../engine/systems/floors';
import { TILE, floorOf, lanternRadius } from '../engine/systems/floors';
import { BALANCE } from '../engine/data/balance';

import type { Camera } from '../lantern/scene/camera';
import { makeScene, makeOccluderGrid, setSolid, type Light, type Material, type Scene } from '../lantern/scene/scene';
import { LAYER_BOARD, type Sprite, type Tint, type UVRect } from '../lantern/scene/sprite';
import { pieceBaseSprites, wallBlockSprites, contactShadowSprite } from '../lantern/scene/piece';
import { BAKED_RIM_HEIGHT, boardSlabSprites, ledgeFace } from '../lantern/scene/board';
import { mushroomEmitter, mushroomSpots, sconceEmitter, wispEmitter, wispPaths, hashCoord } from '../lantern/scene/emitters';

// -------------------------------------------------------------------------
// MATERIAL IDS — stated once, so the builder and the loader cannot disagree
// -------------------------------------------------------------------------

export const MAT_GROUND = 'ground';
export const MAT_WALL = 'wall';
export const MAT_HERO = 'hero';
/** A 1x1 opaque white texel. Tinted black, it is the fog; it is also anything
 *  that needs a flat quad and no art. */
export const MAT_BLANK = 'blank';

/** The PROCEDURAL frame and rim — `lantern/scene/board.ts`'s generators. */
export const MAT_FRAME = 'frame';
export const MAT_RIM = 'rim';

// -------------------------------------------------------------------------
// THE BLENDER-BAKED FURNITURE (§11's "material variety", §19.1)
//
// Every id here is REQUESTED unconditionally by `materials.ts` and DRAWN only
// where `has()` says it arrived. That asymmetry is the whole safety property:
// `web/public/art/materials/` is a build artifact regenerated by `npm run
// art:board`, so a fresh clone has none of these and must degrade to the
// procedural stand-ins rather than to a blank quad.
//
// A baked shape never shares an id with the generator it replaces. If it did,
// `has()` would always answer true — the generator is registered
// synchronously at library creation — and the builder could never tell which
// one it actually got.
// -------------------------------------------------------------------------

/** `board_frame`: the slab's outline, mitred, beaded and rebated. */
export const MAT_FRAME_BAKED = 'frame:baked';
/** `board_frame_brass`: the inlay strip and the four corner brackets. */
export const MAT_FRAME_BRASS = 'frame:brass';
/** `board_rim`: the slab's own edge, in timber, four tiles to a repeat. */
export const MAT_RIM_BAKED = 'rim:baked';
/** `board_rim_brass`: the strap and its bolt heads at every four-tile seam. */
export const MAT_RIM_BRASS = 'rim:brass';
/** `wall_top` / `wall_top_worn`: the top face of a wall block. */
export const MAT_WALL_TOP = 'wall:top';
export const MAT_WALL_TOP_WORN = 'wall:top:worn';
/** `wall_face` / `wall_face_chipped`: the face the lantern rakes across. */
export const MAT_WALL_FACE = 'wall:face';
export const MAT_WALL_FACE_CHIPPED = 'wall:face:chipped';
/** The three turned bases a piece stands in: rank and file, hero, boss (§15). */
export const MAT_PLINTH = 'plinth';
export const MAT_PLINTH_SMALL = 'plinth:small';
export const MAT_PLINTH_LARGE = 'plinth:large';

/**
 * `bake.py`'s MARGIN — the empty space a FREE-STANDING shape carries.
 *
 * A plinth is sized by the engine from its own diameter, so Cycles renders it
 * with 4% of slack around the silhouette for its filter to put the
 * anti-aliased edge in. Drawing that texture at the plinth's diameter would
 * therefore render the plinth itself 4% small; the quad has to be the frame,
 * not the shape.
 */
const BAKE_MARGIN = 1.04;

// -------------------------------------------------------------------------
// THE STONE IS PER-GATE. THE BAKE'S STONE IS NOT.
//
// `bake.py` renders every wall shape out of ONE shared palette — `STONE =
// (0.50, 0.47, 0.46)`, and that is the literal, flat albedo those four PNGs
// carry (measured: mean 187.5/182.4/180.6 sRGB with a total spread of ONE BYTE
// of luminance across all 1024x1024 of it; every scrap of shape in a baked wall
// lives in its normal and material maps, none of it in its colour). The painted
// tiles are per-gate and far darker: `hollow_wall.jpg` is 31.6 mean luminance
// against the bake's 183.3, so a Hollow Gate wall came out 5.8x too light —
// pale limestone where §12 wants dark cave rock. In LINEAR light, which is what
// the surface actually bounces, the same pair is 27x.
//
// That is not a taste complaint. ENGINE_PLAN §12 says the hero's lantern is the
// ONLY significant light, and `buildFloorScene`'s room lamp was cut 0.32 -> 0.12
// on exactly that argument (its +51% of frame luminance against the whole
// emitter set's +4.5%). A wall reflecting 5.8x what the art says it reflects
// picks that lamp up from across the board and hands back the ground that
// retuning bought.
//
// THE FIX IS A MULTIPLY, AND ON A FLAT ALBEDO A MULTIPLY IS A RE-BAKE. Because
// the bake's colour is constant, `tint * STONE` is bit-for-bit what Cycles would
// have written had `shape(..., colour=<this gate's stone>)` been passed instead
// — no detail is lost, because there is no detail in there to lose. So the tint
// is not a correction laid over the asset; it IS the asset's `colour=`, moved to
// where the renderer knows which gate it is drawing.
//
// WHY THE NUMBERS ARE LINEAR AND NOT BYTES, which is the trap. Both the painted
// tile and the bake upload `SRGB8_ALPHA8`, so `texture()` hands the shader
// LINEAR reflectance and `vTint` multiplies it there
// (`passes/lighting.ts`: `vec4 albedo = texture(uAlbedo, vUV) * vTint`). Taking
// the ratio in bytes instead — 31.6/183.3 = 0.172 for Hollow — leaves the wall
// at sRGB 83 rather than 36, i.e. still 2.6x too bright, and the whole exercise
// half-done while looking finished.
// -------------------------------------------------------------------------

/**
 * `tools/art/blender/bake.py`'s `STONE`, in Blender's LINEAR sRGB.
 *
 * Restated rather than imported for the same reason `board.ts` restates
 * `BAKED_FRAME`: nothing joins the two programs at runtime, so a change on
 * either side has to fail a test rather than a screenshot. `bakeStone.test.ts`
 * reads the tuple straight out of `bake.py` and compares.
 */
export const BAKE_STONE: readonly [number, number, number] = [0.5, 0.47, 0.46];

/**
 * Each gate's stone, as the MEAN LINEAR albedo of its own `<gate>_wall.jpg`.
 *
 * Measured off the shipped art, not chosen — `floorScene.test.ts` decodes the
 * five JPEGs and re-derives every row, so these cannot drift from the paintings
 * they describe. Recorded alongside, as byte luminance, because that is the
 * number the eye and the commit log argue in:
 *
 *   gate      wall lum   ground lum   wall/ground     the material
 *   verdant      29.8        100.0        0.130       mossed stone
 *   hollow       31.6        113.0        0.105       raw hewn rock
 *   sunken       39.2        118.3        0.135       wet cut stone, silt
 *   storm        36.0        145.4        0.080       cracked slate, frost
 *   abyss         7.9         24.2        0.233       blackened basalt
 *
 * The ground column is the check rather than an input: nothing tints the floor,
 * so a wall matched to its own gate's wall art keeps that gate's authored
 * wall:ground contrast by construction. It is also why one tint serves both a
 * block's top and its front — they are the same stone, and (see above) the same
 * flat texture.
 */
export const GATE_WALL_ALBEDO: Record<string, readonly [number, number, number]> = {
  verdant: [0.01225, 0.01939, 0.01118],
  hollow: [0.0217, 0.01568, 0.02392],
  sunken: [0.02787, 0.02713, 0.03657],
  storm: [0.02351, 0.02272, 0.03165],
  abyss: [0.00301, 0.00228, 0.0037],
};

/**
 * The stone a gate with no measured wall art gets: the mean of the five above.
 *
 * NOT white, and that is the whole point of it existing. A sixth gate added
 * without tiles would otherwise fall through to the bake's own palette and
 * resurrect the pale-limestone defect this block exists to remove — silently,
 * on one gate, which is the worst way to ship it. A placeholder in the right
 * neighbourhood is a better failure than a bug in the wrong one.
 */
export const DEFAULT_WALL_ALBEDO: readonly [number, number, number] = [0.017668, 0.01744, 0.021404];

/**
 * What to multiply a baked wall's flat STONE by so it reads as this gate's rock.
 *
 * Alpha is 1: this changes what the surface is made of, never whether it is
 * there.
 */
export function wallTint(gateId: string): Tint {
  const stone = GATE_WALL_ALBEDO[gateId] ?? DEFAULT_WALL_ALBEDO;
  return [stone[0] / BAKE_STONE[0], stone[1] / BAKE_STONE[1], stone[2] / BAKE_STONE[2], 1];
}

/** The icon a tile shows when it is not plain floor, or null for plain floor. */
export function objectIcon(tile: string): string | null {
  switch (tile) {
    case TILE.START:
      return 'door';
    case TILE.STAIRS:
      return 'stairs';
    case TILE.BOSS:
      return 'boss';
    case TILE.BREAKABLE:
      return 'barrel';
    case TILE.CHEST:
      return 'chest';
    case TILE.SHRINE:
      return 'shrine';
    case TILE.EVENT:
      return 'event';
    case TILE.SECRET:
      return 'secret';
    default:
      return null;
  }
}

export function iconTextureId(icon: string): string {
  return `icon:${icon}`;
}

/** Which painted figure stands on a unit's plinth. */
export function unitTextureId(unit: FloorUnit): string {
  if (unit.kind === 'merchant') return 'sprite:merchant';
  if (unit.kind === 'tamer') return 'sprite:tamer';
  return unit.speciesId ? `monster:${unit.speciesId}` : 'sprite:tamer';
}

// -------------------------------------------------------------------------
// THE SNAPSHOT — the linear scans, paid once
// -------------------------------------------------------------------------

export interface FloorSnapshot {
  gateId: string;
  floorIndex: number;
  /** Tile rows, padded to `width` with WALL so ragged authored grids are square. */
  rows: string[];
  width: number;
  height: number;
  /** Bare "x,y" keys — the floor prefix is already stripped. */
  revealed: Set<string>;
  opened: Set<string>;
  broken: Set<string>;
  units: FloorUnit[];
  /** Where the reducer says the hero is. The renderer glides toward it. */
  heroTile: { x: number; y: number };
  /** Pool radius in tiles — the same expression `FloorScreen` gives LightLayer. */
  lightCells: number;
  bossDefeated: boolean;
}

function bareKeys(scoped: readonly string[], prefix: string): Set<string> {
  const out = new Set<string>();
  for (const key of scoped) if (key.startsWith(prefix)) out.add(key.slice(prefix.length));
  return out;
}

/**
 * Everything the builder needs, with every `Array.includes` already paid for.
 *
 * Cheap enough to run per state change and far too expensive to run per tile
 * per frame, which is exactly what the DOM path does today — see the note at
 * the top of the file. Call it from a `useMemo` keyed on the arrays' identity;
 * the reducer is immutable, so identity changes exactly when the contents do.
 */
export function snapshotFloor(exp: Expedition, player: Character, bossDefeated: boolean): FloorSnapshot {
  const floor = floorOf(exp);
  const width = Math.max(1, ...floor.grid.map((r) => r.length));
  const height = floor.grid.length;
  const rows = floor.grid.map((r) => (r.length >= width ? r : r + TILE.WALL.repeat(width - r.length)));
  const prefix = `${exp.gateId}:${exp.floorIndex}:`;
  return {
    gateId: exp.gateId,
    floorIndex: exp.floorIndex,
    rows,
    width,
    height,
    revealed: bareKeys(exp.revealed, prefix),
    opened: bareKeys(exp.opened, prefix),
    broken: bareKeys(exp.broken, prefix),
    // NOTE: `litTiles` is deliberately NOT called here. On the DOM path it
    // decides which tiles look lit; on this one the lantern is a real light
    // and the shader answers that question per fragment. Calling it anyway
    // would be a BFS per state change to produce a Set nothing reads.
    units: exp.units,
    heroTile: { x: exp.x, y: exp.y },
    // Stated once in FloorScreen and mirrored here on purpose: the pool's
    // radius IS the move budget (see the comment on `reachCells` there), so
    // the light closing in as movement is spent is a game reading, not a
    // lighting one, and it must survive the port.
    lightCells: exp.movLeft + 0.7 + (lanternRadius(player) - BALANCE.lanternRadius),
    bossDefeated,
  };
}

export function tileAtSnapshot(snap: FloorSnapshot, x: number, y: number): string {
  if (y < 0 || y >= snap.height) return TILE.WALL;
  const row = snap.rows[y];
  if (x < 0 || x >= row.length) return TILE.WALL;
  return row[x];
}

/**
 * What a tile RESOLVES to once the expedition's history is applied.
 *
 * The same collapse `FloorScreen` performs inline: an opened chest is floor, a
 * smashed barrel is floor, a spawn marker whose unit is alive is floor (the
 * unit is drawn separately), a defeated gate warden is floor, and a secret is
 * only itself while you are standing next to it.
 */
export function resolvedTile(snap: FloorSnapshot, x: number, y: number, heroTile: { x: number; y: number }): string {
  const ch = tileAtSnapshot(snap, x, y);
  const key = `${x},${y}`;
  if (ch === TILE.WALL || ch === TILE.FLOOR) return ch;
  if (snap.opened.has(key) && (ch === TILE.CHEST || ch === TILE.SHRINE || ch === TILE.EVENT || ch === TILE.BOSS || ch === TILE.SECRET)) {
    return TILE.FLOOR;
  }
  if (ch === TILE.BREAKABLE && snap.broken.has(key)) return TILE.FLOOR;
  if (ch === TILE.SECRET) {
    const adjacent = Math.abs(x - heroTile.x) + Math.abs(y - heroTile.y) === 1;
    return adjacent ? ch : TILE.FLOOR;
  }
  if (ch === TILE.BOSS && snap.bossDefeated) return TILE.FLOOR;
  if (ch === TILE.ENEMY || ch === TILE.MINIBOSS || ch === TILE.TAMER || ch === TILE.MERCHANT) return TILE.FLOOR;
  return ch;
}

// -------------------------------------------------------------------------
// THE BUILD
// -------------------------------------------------------------------------

export interface FloorSceneOptions {
  camera: Camera;
  /** Seconds. Drives flicker and drift; a fixed value gives a fixed frame. */
  time: number;
  /** Where the hero PIECE is right now, mid-glide. Usually not his tile. */
  heroAt: { x: number; y: number };
  /** Only ids present here are drawn — an unloaded texture is silently skipped. */
  materials: Map<string, Material>;
  ambient?: number;
  lanternIntensity?: number;
  roomLamp?: number;
  /** §12.4's faint scenery. Off is a legal, duller board. */
  emitters?: boolean;
  mushroomDensity?: number;
  sconceDensity?: number;
  wispCount?: number;
}

/** Frame width around the play area, in tiles. Matches the harness's slab. */
export const BOARD_BORDER = 1.35;
export const BOARD_THICKNESS = 0.5;
/** The shortest a wall block can stand. Fed to `Scene.occluderHeight`. */
export const BLOCK_MIN_HEIGHT = 0.66;

/**
 * Per-block height, hashed off the tile.
 *
 * Blocks all exactly one height read as an extrusion of the floor plan; a few
 * percent of variation reads as separate objects somebody placed. Hashed, not
 * random, for the reason every generator in this engine is: a frame must be a
 * pure function of state, or no pixel diff in this project means anything.
 */
export function blockHeight(x: number, y: number): number {
  return BLOCK_MIN_HEIGHT + hashCoord(x, y, 41) * 0.13;
}

/** Window the shared tile texture per cell so neighbours do not visibly repeat. */
function cellUv(x: number, y: number): UVRect {
  const u = ((x % 4) + 4) % 4;
  const v = ((y % 4) + 4) % 4;
  return { u0: u / 4, v0: v / 4, u1: (u + 1) / 4, v1: (v + 1) / 4 };
}

const FULL_UV: UVRect = { u0: 0, v0: 0, u1: 1, v1: 1 };

/** Which cut of stone a wall block shows, and whether it is baked at all. */
export interface WallCut {
  top: string;
  face: string;
  /** True when BOTH halves are baked — the fallback is all or nothing. */
  baked: boolean;
}

/**
 * Pick a block's two faces out of the baked stone, or fall back to the tile art.
 *
 * ALL OR NOTHING, and that is the only interesting decision here.
 * `wallBlockSprites` paints one texture onto both the top and the front, so a
 * half-arrived bake — `wall_top` in, `wall_face` still in flight — would put a
 * lying top-face render onto an upright quad, whose normals mean something
 * completely different (LYING maps texture G to board y, UPRIGHT maps it to
 * board z). Every wall on the board would light as though tipped on its back
 * for as long as the second fetch took. So the two are taken together or
 * neither is taken.
 *
 * The worn and chipped variants are HASHED off the tile rather than random, for
 * the reason every generator in this engine is: a frame must be a pure function
 * of state or no pixel diff in this project means anything. They are what
 * replaces `cellUv`'s 4x4 window on the baked path — a wall of identical blocks
 * reads as an extrusion of the floor plan, and a quarter of them cut differently
 * reads as blocks somebody laid.
 */
export function wallCut(x: number, y: number, has: (id: string) => boolean): WallCut {
  if (!has(MAT_WALL_TOP) || !has(MAT_WALL_FACE)) return { top: MAT_WALL, face: MAT_WALL, baked: false };
  const worn = hashCoord(x, y, 29) < 0.28;
  return {
    top: worn && has(MAT_WALL_TOP_WORN) ? MAT_WALL_TOP_WORN : MAT_WALL_TOP,
    face: worn && has(MAT_WALL_FACE_CHIPPED) ? MAT_WALL_FACE_CHIPPED : MAT_WALL_FACE,
    baked: true,
  };
}

/**
 * Which turned base a piece stands in, and how wide to draw it.
 *
 * §15's three sizes are rank, hero and boss, and the bake makes them three
 * different TREATMENTS rather than one base at three zooms — so a miniboss
 * gets the stepped `plinth_large` and grows to suit it. Falls back to the
 * generated disc, at the radius that shipped, when there is no bake.
 */
export function plinthFor(
  kind: 'hero' | 'miniboss' | 'unit',
  has: (id: string) => boolean,
): { id: string; radius: number } {
  const bakedId = kind === 'hero' ? MAT_PLINTH : kind === 'miniboss' ? MAT_PLINTH_LARGE : MAT_PLINTH_SMALL;
  const radius = kind === 'hero' ? 0.4 : kind === 'miniboss' ? 0.44 : 0.36;
  if (!has(bakedId)) return { id: 'base', radius };
  return { id: bakedId, radius: radius * BAKE_MARGIN };
}

/**
 * One frame of a real expedition floor, as a Scene.
 *
 * Rebuilt from state every frame rather than mutated in place — the same
 * discipline the game's reducer keeps, and the reason the renderer can be
 * stateless about the world and still survive a lost GL context.
 */
export function buildFloorScene(snap: FloorSnapshot, o: FloorSceneOptions): Scene {
  const has = (id: string) => o.materials.has(id);
  const sprites: Sprite[] = [];
  const lights: Light[] = [];
  // This gate's rock, as a multiplier on the shared STONE the bake carries.
  // Computed once: it is the same for every block on the floor, and both faces
  // of every one of them.
  const stone = wallTint(snap.gateId);

  // --- the occupancy grid ------------------------------------------------
  // Walls only. A barrel is a painted object standing in the middle of a tile,
  // not the tile — the DOM path had to special-case that with a separate
  // occluder selector, and on a grid the honest answer is that it is too small
  // to be a tile-sized occluder at all.
  const grid = makeOccluderGrid(snap.width, snap.height);
  for (let y = 0; y < snap.height; y++) {
    for (let x = 0; x < snap.width; x++) {
      if (tileAtSnapshot(snap, x, y) === TILE.WALL) setSolid(grid, x, y, true);
    }
  }

  // --- the slab ----------------------------------------------------------
  // The baked frame and rim if they have arrived, the generated ones if not.
  // `boardSlabSprites` takes `frameWindows` as the OPT-IN, so leaving it
  // undefined is byte-for-byte the board that shipped before the bake existed.
  const bakedRim = has(MAT_RIM_BAKED);
  sprites.push(
    ...boardSlabSprites(
      {
        width: snap.width,
        height: snap.height,
        border: BOARD_BORDER,
        thickness: BOARD_THICKNESS,
        frameTextureId: MAT_FRAME,
        frameWindows: has(MAT_FRAME_BAKED)
          ? {
              textureId: MAT_FRAME_BAKED,
              brassTextureId: has(MAT_FRAME_BRASS) ? MAT_FRAME_BRASS : undefined,
            }
          : undefined,
        rimTextureId: bakedRim ? MAT_RIM_BAKED : MAT_RIM,
        rimBrassTextureId: bakedRim && has(MAT_RIM_BRASS) ? MAT_RIM_BRASS : undefined,
        // The bake is 4 tiles long and 0.34 tall; this slab is 0.5 thick. Scale
        // the repeat length by the same factor so the strap's bolt heads stay
        // round instead of stretching into ovals. The procedural rim has no
        // authored aspect to protect, so it keeps the flat 4.
        rimRepeat: bakedRim ? (4 * BOARD_THICKNESS) / BAKED_RIM_HEIGHT : undefined,
        tableTextureId: 'table',
        shadowTextureId: 'blockshadow',
        tableGrain: 3.2,
      },
      o.camera,
    ),
  );

  // --- the tiles ---------------------------------------------------------
  for (let y = 0; y < snap.height; y++) {
    for (let x = 0; x < snap.width; x++) {
      const key = `${x},${y}`;
      if (!snap.revealed.has(key)) {
        // Fog: present, and dark. See the file header — an absent quad would
        // show the frame's timber through the hole in the board.
        sprites.push({
          position: { x, y, z: 0 },
          size: { x: 1, y: 1 },
          pivot: { x: 0, y: 0 },
          uv: FULL_UV,
          textureId: MAT_BLANK,
          tint: [0, 0, 0, 1],
          layer: LAYER_BOARD,
        });
        continue;
      }
      const raw = tileAtSnapshot(snap, x, y);
      if (raw === TILE.WALL) {
        const h = blockHeight(x, y);
        const ahead = tileAtSnapshot(snap, x, y + 1);
        // A face buried behind a taller neighbour costs a quad and a batch
        // break to draw something nobody can see — but ONLY if the neighbour
        // is at least as tall, or the sliver that shows through is whatever is
        // under the board, which reads as a bright glitch line.
        const front = ahead !== TILE.WALL || blockHeight(x, y + 1) < h;
        const cut = wallCut(x, y, has);
        sprites.push(
          ...wallBlockSprites(
            { x, y },
            {
              textureId: cut.top,
              height: h,
              // A bake IS one tile. The 4x4 window exists to stop the painted
              // tile art visibly repeating; the worn/chipped variants below do
              // that job for the baked stone instead.
              topUv: cut.baked ? FULL_UV : cellUv(x, y),
              frontUv: cut.baked ? FULL_UV : { u0: cellUv(x, y).u0, v0: 0.5, u1: cellUv(x, y).u1, v1: 1 },
              // `wallBlockSprites` puts ONE texture on both faces. A baked
              // block is two separate shapes — `wall_top` lying and `wall_face`
              // upright — so the face is pushed below instead.
              front: front && !cut.baked,
              // NO FAKE SHADING on the baked path, and this is still true: the
              // pair below darkened the front face relative to the top to stand
              // in for an ambient occlusion the painted tile art could not
              // carry, and `wall_face` carries real AO in its material map's
              // alpha and real relief in its normal.
              //
              // What the baked path gets instead is a PALETTE, not a shade —
              // one value, identical on the top and the front, saying which
              // gate's rock this block is cut from. It cannot stand in for AO
              // because it does not distinguish the two faces; see the block
              // comment on `GATE_WALL_ALBEDO`.
              topTint: cut.baked ? stone : [0.88, 0.88, 0.92, 1],
              frontTint: cut.baked ? stone : [0.78, 0.78, 0.84, 1],
              shadowTextureId: 'blockshadow',
              shadowStrength: 0.55,
            },
          ),
        );
        // The block's front face, as what `board.ts` says every vertical
        // surface in the game is: a ledge closing a height discontinuity. Same
        // rect, pivot and layer `wallBlockSprites` would have given it — the
        // only difference is that it gets its own texture.
        if (front && cut.baked) {
          sprites.push(
            ledgeFace({ x, width: 1, y: y + 1, top: h, bottom: 0, textureId: cut.face, uv: FULL_UV, tint: stone }),
          );
        }
        continue;
      }

      sprites.push({
        position: { x, y, z: 0 },
        size: { x: 1, y: 1 },
        pivot: { x: 0, y: 0 },
        uv: cellUv(x, y),
        textureId: MAT_GROUND,
      });

      const tile = resolvedTile(snap, x, y, snap.heroTile);
      const icon = objectIcon(tile);
      if (icon) {
        const id = iconTextureId(icon);
        if (has(id)) {
          // A thing standing ON the tile, so it gets the same three-part
          // treatment a piece gets minus the plinth: shadow, then figure.
          // Without the contact shadow it reads as a sticker (§15.1).
          sprites.push(
            contactShadowSprite({ x: x + 0.5, y: y + 0.5 }, 'shadow', { radius: 0.34, strength: 0.62, height: 0 }),
            {
              position: { x: x + 0.5, y: y + 0.5, z: 0 },
              size: { x: 0.78, y: 0.78 },
              pivot: { x: 0.5, y: 1 },
              billboard: true,
              uv: FULL_UV,
              textureId: id,
            },
          );
        }
      }
    }
  }

  // --- the pieces --------------------------------------------------------
  for (const unit of snap.units) {
    if (!snap.revealed.has(`${unit.x},${unit.y}`)) continue;
    const id = unitTextureId(unit);
    const plinth = plinthFor(unit.kind === 'miniboss' ? 'miniboss' : 'unit', has);
    sprites.push(
      ...pieceBaseSprites({ x: unit.x + 0.5, y: unit.y + 0.5 }, plinth.id, 'shadow', { radius: plinth.radius }),
    );
    if (has(id)) {
      sprites.push({
        position: { x: unit.x + 0.5, y: unit.y + 0.5, z: 0.11 },
        size: { x: 1.0, y: 1.0 },
        pivot: { x: 0.5, y: 1 },
        billboard: true,
        uv: FULL_UV,
        textureId: id,
      });
    }
  }

  // The hero, at his INTERPOLATED position — see `render/walk.ts`. The reducer
  // has already moved him; the piece is still on its way, and so is the light,
  // which is the entire reason the glide was worth keeping.
  const hero = { x: o.heroAt.x + 0.5, y: o.heroAt.y + 0.5 };
  const heroPlinth = plinthFor('hero', has);
  sprites.push(...pieceBaseSprites(hero, heroPlinth.id, 'shadow', { radius: heroPlinth.radius, thickness: 0.11 }));
  if (has(MAT_HERO)) {
    sprites.push({
      position: { x: hero.x, y: hero.y, z: 0.11 },
      size: { x: 1.1, y: 1.55 },
      pivot: { x: 0.5, y: 1 },
      billboard: true,
      uv: FULL_UV,
      textureId: MAT_HERO,
    });
  }

  // --- the light ---------------------------------------------------------
  // THE LAST LANTERN. One bright source, carried, above the piece's head.
  lights.push({
    position: { x: hero.x, y: hero.y, z: 0.9 },
    colour: [1, 0.62, 0.28],
    // 7, not the harness's 9, and the difference is the REACH rather than a
    // change of taste. `lightCells` on a real floor is around 4.7 tiles
    // against the harness's 7, and a shorter falloff window puts more of the
    // same radiance on the tiles nearest the flame — so the pool came out
    // near-white on stone that should read as lit sandstone.
    intensity: o.lanternIntensity ?? 7,
    radius: 0.18,
    // The pool ends exactly where the walk ends, which is the reading
    // FloorScreen's `reachCells` established and this must not quietly change.
    reach: Math.max(2, snap.lightCells),
  });

  // THE ROOM the board is sitting in, not the dungeon (§15.1). It casts, which
  // is what keeps it out of the fiction: raking from the near-left, the slab's
  // own border blocks shadow the interior from it completely, so it lands on
  // the table, the rim and the frame and stops dead at the wall.
  // Dimmer than the harness's 1.0, and for a reason the harness could not see:
  // its board had a solid ring of border blocks, so the lamp genuinely stopped
  // at the wall. A REAL floor's outer wall is one block tall and the lamp sits
  // 15 tiles up, so the ray from an interior tile clears it almost at once and
  // a cold wash reaches the dungeon floor — which is precisely the thing §12
  // says must not happen. Lowered rather than removed, because without it the
  // rim, the frame and the table are lit by ambient alone and every bit of
  // §11's edge work is invisible.
  //
  // MEASURED, AND LEFT ALONE, WHICH IS A DELIBERATE PAIR. On a fully revealed
  // Hollow Gate floor at 962x600 the lamp is worth **+51% of the whole frame's
  // mean luminance**; the emitters below, all of them together, are worth
  // +4.5%. So when the board reads "pale and washed rather than dark with
  // pools" — ENGINE_PLAN §18.1 item 2 — the sconces are not what is doing it
  // any more, and were not the biggest part of it on a real floor even before
  // this pass. This lamp is.
  //
  // Not changed here because §15.1 calls it "a design decision and not a knob"
  // and §20 set this number three commits ago with a stated argument. The
  // number is recorded rather than acted on, so whoever takes that decision
  // takes it with the measurement in front of them. The honest fix is not a
  // smaller value either: it is §14's per-tile height field, which would let
  // the outer wall actually stop the ray the way the harness's board did.
  // 0.32 -> 0.12 on Paul's call, with the measurement in front of him: at 0.32
  // this lamp was worth +51% of the frame's mean luminance against the whole
  // emitter set's +4.5%, and §12 says the hero's lantern is the ONLY
  // significant light. Not zero, though — this is the light of the ROOM THE
  // BOARD IS IN, not a light in the fiction, and at zero the board stops
  // resting on a table and starts floating in a void.
  //
  // IT SHOULD EVENTUALLY MOVE. Paul: *"the room lighting might even change from
  // time to time tbh"*. A real room's light does — someone shifts a lamp, a
  // fire settles, daylight goes. Deliberately NOT implemented as a wobble on
  // this constant: a slow drift with no cause reads as a bug, and the honest
  // version is a room whose light has a reason (time of day at the inn, a fire
  // in the hearth) driven from game state rather than from a sine. The real
  // prerequisite is still §14's height field, so the board's own walls block
  // this lamp instead of it washing the play area from outside.
  const roomLamp = o.roomLamp ?? 0.12;
  if (roomLamp > 0) {
    lights.push({
      position: { x: -5, y: snap.height + 8, z: 15 },
      colour: [0.6, 0.68, 1],
      intensity: roomLamp,
      radius: 1.4,
      reach: Math.max(95, snap.width * 4),
    });
  }

  // --- the scenery (§12.4) ----------------------------------------------
  if (o.emitters !== false) {
    const revealedOnly = (x: number, y: number) => snap.revealed.has(`${Math.floor(x)},${Math.floor(y)}`);

    for (const spot of mushroomSpots(grid, { density: o.mushroomDensity ?? 0.3 })) {
      if (!revealedOnly(spot.x, spot.y)) continue;
      const e = mushroomEmitter(spot, { time: o.time, seed: spot.x * 3.1 + spot.y });
      if (has('mushroom')) sprites.push(...e.sprites);
      lights.push(e.light);
    }

    const sconceDensity = o.sconceDensity ?? 0.12;
    if (sconceDensity > 0) {
      for (let y = 0; y < snap.height; y++) {
        for (let x = 0; x < snap.width; x++) {
          if (tileAtSnapshot(snap, x, y) !== TILE.WALL) continue;
          // Only where the block actually draws a front face, or the flame is
          // a light floating inside solid rock.
          if (tileAtSnapshot(snap, x, y + 1) === TILE.WALL) continue;
          if (!snap.revealed.has(`${x},${y + 1}`)) continue;
          if (hashCoord(x, y, 17) > sconceDensity) continue;
          const e = sconceEmitter({ x, y }, { time: o.time, seed: x * 1.7 + y * 2.3 });
          if (has('flame')) sprites.push(...e.sprites);
          lights.push(e.light);
        }
      }
    }

    const wispCount = o.wispCount ?? 5;
    if (wispCount > 0) {
      const paths = wispPaths(grid, { count: wispCount, radius: 2.6 });
      for (const path of paths) {
        const e = wispEmitter(path, o.time);
        if (has('wisp')) sprites.push(...e.sprites);
        lights.push(e.light);
      }
    }
  }

  return makeScene(o.camera, {
    sprites,
    materials: o.materials,
    occluders: grid,
    occluderHeight: BLOCK_MIN_HEIGHT,
    lights,
    time: o.time,
    ambient: o.ambient ?? 0.06,
  });
}
