// =========================================================================
// THE MATERIAL LIBRARY — where a Scene's texture ids get pixels.
//
// Split from `floorScene.ts` on purpose. The scene builder is pure and knows
// only ids; this file is the one that touches `gl`, loads PNGs off the network
// and holds handles that have to be freed. Keeping them apart is what lets the
// builder be unit-tested with a `Map` of fakes and no graphics context.
//
// TWO UPLOAD RULES, and both of them have cost hours somewhere in this
// project:
//
//   COLOUR is SRGB8_ALPHA8. Everything past the sampler is linear-light, so
//   handing it gamma-encoded bytes makes every midtone too bright.
//
//   NORMALS are RGBA8, never sRGB. A normal map is three numbers that happen
//   to live in a colour texture; an sRGB decode turns 0.5 — "no tilt on this
//   axis" — into 0.21 and tips every surface.
//
// ASYNCHRONY IS NOT AN ERROR STATE. `SpriteBatcher.draw` skips a batch whose
// texture id is missing from the map, so a floor renders the moment the
// procedural furniture exists and gains its painted tiles, icons and figures
// as they arrive. Nothing waits, nothing flashes, and a 404 on one monster
// costs that monster and nothing else.
//
// HOW THE BAKED MAPS GET HERE, which is a real question and not a detail.
// `tools/art/bake.mjs` writes normal/height/AO/albedo into `web/art-staging/`,
// which is gitignored precisely so Vite does not sweep every intermediate into
// `dist`. `lantern-board.html` reaches staging with `/@fs/`, and that is a DEV
// SERVER FEATURE — an absolute path off the developer's own disk. It cannot
// ship, so the game path must not copy it.
//
// So the baker PUBLISHES: after writing staging it copies the two maps the
// renderer actually samples — `_normal.png` and `_albedo.png` — into
// `web/public/art/materials/<set>/`, and leaves height and AO behind as the
// intermediates they are. That directory is a build artifact: gitignored,
// regenerated byte-for-byte by `npm run art:bake`, and shipped by an ordinary
// `vite build` because it is under `public/`.
//
// EVERY ONE OF THOSE FETCHES IS ALLOWED TO 404. A checkout that has never
// baked gets the original albedo and a flat normal, which is exactly the board
// that shipped before this file learned about relief. Missing bakes degrade;
// they never throw.
// =========================================================================

import type { Material } from '../lantern/scene/scene';
import { createRGBATexture } from '../lantern/gl/procedural';
import {
  baseDiscNormalPixels,
  baseDiscPixels,
  blockShadowPixels,
  contactShadowPixels,
} from '../lantern/scene/piece';
import {
  boardFrameNormalPixels,
  boardFramePixels,
  boardRimNormalPixels,
  boardRimPixels,
  fieldToAlbedo,
  fieldToNormals,
  woodField,
} from '../lantern/scene/board';
import { flamePixels, mushroomPixels, wispPixels } from '../lantern/scene/emitters';
import { TILE_TEXTURES, SPRITE_ART, ICON_ART } from '../art/iconArt';
import { PAINTED_MONSTERS } from '../art/paintedCharacters';
import { MAT_BLANK, MAT_GROUND, MAT_HERO, MAT_WALL, iconTextureId } from './floorScene';

export interface MaterialLibrary {
  materials: Map<string, Material>;
  /** Queue a colour texture for `id` from `url`. Idempotent; a repeat is free. */
  request(id: string, url: string, extra?: Partial<Material>): void;
  /** True once at least the procedural furniture is up. */
  ready: boolean;
  dispose(): void;
}

// -------------------------------------------------------------------------
// THE BAKED MAPS — where they live, and which assets have them
// -------------------------------------------------------------------------

/** Published by `tools/art/bake.mjs`. Mirrors `web/art-staging/materials/`. */
export const BAKED_ROOT = 'art/materials';

/**
 * The sets `bake.mjs` knows about, keyed by the `web/public/art/` directory
 * they read from — which is also the staging subdirectory it writes to, and
 * therefore the published one. Stated here rather than derived so that a set
 * added to the baker and not to the game fails as a 404 on one asset instead
 * of as a silent path that never matches anything.
 */
const BEVEL_SETS = new Set(['sprites', 'monsters', 'heroes', 'npcs']);
const TILE_SETS = new Set(['tiles']);

export interface BakedRef {
  set: string;
  name: string;
  /** True on the EDT-bevel path, which is the only one that emits an albedo. */
  bevel: boolean;
}

/**
 * Which bake, if any, belongs to a piece of source art — from its URL alone.
 *
 * Pure and string-only on purpose: it is the single place that encodes the
 * baker's output convention (`<set>/<source basename>_<map>.png`), it is the
 * thing most likely to drift when either side is renamed, and a unit test can
 * hold it to the convention without a graphics context or a file on disk.
 *
 * A URL outside the baked sets — every icon, every card, every backdrop —
 * returns null and is loaded exactly the way it always was. No wasted fetch.
 */
export function bakedRef(url: string): BakedRef | null {
  const m = /(?:^|\/)art\/([a-z]+)\/([^/]+)\.(?:png|jpe?g)$/i.exec(url);
  if (!m) return null;
  const set = m[1].toLowerCase();
  if (BEVEL_SETS.has(set)) return { set, name: m[2], bevel: true };
  // A tile is luminance->Sobel: it has no alpha to repair, so `bake.mjs` writes
  // no `_albedo.png` for it and asking for one would 404 on every floor load.
  if (TILE_SETS.has(set)) return { set, name: m[2], bevel: false };
  return null;
}

/**
 * How much of a DERIVED tile normal to apply. ENGINE_PLAN §18.2, last item.
 *
 * These maps are luminance->Sobel off art painted under overhead light, and
 * the lantern is not overhead: at knee height N·L on the floor is around 0.05,
 * so a 15 degree bump multiplies the term several times over and the floor
 * comes apart into crumpled foil. The stress lab found this and settled at
 * 0.35; this is that number arriving on the shipping path.
 *
 * PER-MATERIAL rather than as the renderer's global default, and the
 * distinction is the whole point: the global also reaches the pieces, whose
 * relief is an EDT bevel on a billboard that faces the camera and never sees a
 * grazing angle. Taming the floor by taming everything would throw away the
 * thing §15.1 calls the single biggest remaining win on the pieces.
 */
export const TILE_RELIEF = 0.35;

/**
 * How much of a piece's bevel to apply. 1, which is the harness's setting and
 * the value §15.1's carved-relief work was judged at — stated explicitly here
 * so no future change to the renderer's global default can move it silently.
 */
export const PIECE_RELIEF = 1;

/** Board frame chamfer, per axis — the slab is not square and one fraction
 *  would make the short edges twice as chamfered as the long ones. */
function frameOptions(width: number, height: number, border: number) {
  const w = width + border * 2;
  const h = height + border * 2;
  return { borderU: (border * 0.86) / w, borderV: (border * 0.86) / h };
}

/**
 * Everything a floor needs that is made of arithmetic rather than art.
 *
 * The table, the frame, the rim, the shadow under a piece, the bevel on its
 * base, and the three emitters. None of these should ever be an art file:
 * they are geometry, and a generated one is deterministic, re-tunable without
 * a re-shoot, and unit-testable as a falloff rather than as a screenshot.
 */
export function createMaterialLibrary(
  gl: WebGL2RenderingContext,
  gateId: string,
  board: { width: number; height: number; border: number },
): MaterialLibrary {
  const materials = new Map<string, Material>();
  const owned: WebGLTexture[] = [];
  let disposed = false;
  /**
   * A material being assembled out of several independent loads.
   *
   * It has to be a record rather than a `materials.set` per arrival, because
   * the albedo and the normal are two requests that finish in either order and
   * whichever landed second used to overwrite the first. That failure is
   * invisible — the piece simply lights flat some of the time — which is the
   * worst kind, so the draft is the fix rather than a load ordering.
   */
  const drafts = new Map<string, { extra: Partial<Material>; albedo: WebGLTexture | null; normal: WebGLTexture | null }>();

  const own = <T extends WebGLTexture>(tex: T): T => {
    owned.push(tex);
    return tex;
  };

  // A single opaque white texel. Tinted black it is the fog; tinted anything
  // it is a flat quad with no art, which is the cheapest possible primitive.
  materials.set(MAT_BLANK, {
    id: MAT_BLANK,
    albedo: own(createRGBATexture(gl, 1, new Uint8Array([255, 255, 255, 255]))),
  });

  materials.set('shadow', {
    id: 'shadow',
    // Alpha-only mask, so NOT sRGB — there is no colour in it to decode.
    albedo: own(createRGBATexture(gl, 96, contactShadowPixels(96), { mipmap: true })),
  });
  materials.set('blockshadow', {
    id: 'blockshadow',
    albedo: own(createRGBATexture(gl, 96, blockShadowPixels(96), { mipmap: true })),
  });
  materials.set('base', {
    id: 'base',
    albedo: own(createRGBATexture(gl, 128, baseDiscPixels(128), { srgb: true, mipmap: true })),
    normal: own(createRGBATexture(gl, 128, baseDiscNormalPixels(128), { mipmap: true })),
    normalStrength: 1,
  });

  const fo = frameOptions(board.width, board.height, board.border);
  materials.set('frame', {
    id: 'frame',
    albedo: own(createRGBATexture(gl, 512, boardFramePixels(512, fo), { srgb: true, mipmap: true })),
    normal: own(createRGBATexture(gl, 512, boardFrameNormalPixels(512, fo), { mipmap: true })),
    normalStrength: 1,
  });
  materials.set('rim', {
    id: 'rim',
    albedo: own(createRGBATexture(gl, 256, boardRimPixels(256), { srgb: true, mipmap: true, repeat: true })),
    normal: own(createRGBATexture(gl, 256, boardRimNormalPixels(256), { mipmap: true, repeat: true })),
    normalStrength: 1,
  });
  const tableField = woodField(256, { grain: 7, warp: 1.5 });
  materials.set('table', {
    id: 'table',
    albedo: own(
      createRGBATexture(gl, 256, fieldToAlbedo(tableField, 256, [30, 21, 14], [92, 64, 40]), {
        srgb: true,
        mipmap: true,
        repeat: true,
      }),
    ),
    normal: own(createRGBATexture(gl, 256, fieldToNormals(tableField, 256, 0.9), { mipmap: true, repeat: true })),
    normalStrength: 1,
  });

  // The faint emitters. Mipmaps ON: a 0.3-tile sprite is a dozen screen pixels
  // and its core would otherwise alias into a scintillating dot as it drifts,
  // which is the firefly case the bloom's Karis average exists for. This is
  // the cheaper half of the same fix.
  //
  // THESE NUMBERS WENT UP AS THE LIGHTS WENT DOWN, and that trade is the entire
  // argument for `Material.emissiveStrength` existing before its map does. The
  // shader adds it to the lit term without any light being involved
  // (`albedo * (ambient + lit + emissive)`), so it buys BRIGHTNESS with no
  // reach whatsoever. §18.1 items 2 and 3 are both a demand for exactly that:
  // emitters that read clearly and light almost nothing. A wisp is now the
  // brightest albedo on the board and the third-faintest light on it.
  for (const [id, pixels, glow] of [
    ['flame', flamePixels(96), 2.7],
    ['mushroom', mushroomPixels(96), 1.9],
    ['wisp', wispPixels(96), 4.2],
  ] as const) {
    materials.set(id, {
      id,
      albedo: own(createRGBATexture(gl, 96, pixels, { srgb: true, mipmap: true })),
      emissiveStrength: glow,
    });
  }

  /**
   * Load one image into a texture.
   *
   * `srgb` IS THE WHOLE REASON THIS TAKES A FLAG, and getting it wrong has
   * cost hours twice in this project — once here and once in the Blender bake,
   * in opposite directions. Colour is `SRGB8_ALPHA8` so the hardware decodes
   * gamma bytes to the linear light everything past the sampler assumes. A
   * normal map is `RGBA8`, always: it is three numbers that happen to live in
   * a colour texture, and an sRGB decode turns 0.5 — "no tilt on this axis" —
   * into 0.21, tipping every surface in the scene.
   *
   * `crossOrigin` is not set: every one of these is same-origin app art, and
   * asking for CORS on a same-origin request is a way to fail on file:// for
   * no benefit.
   */
  function loadImage(url: string, srgb: boolean, done: (tex: WebGLTexture | null) => void): void {
    const img = new Image();
    img.onload = () => {
      if (disposed) return done(null);
      const tex = gl.createTexture();
      if (!tex) return done(null);
      gl.bindTexture(gl.TEXTURE_2D, tex);
      gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, false);
      gl.texImage2D(gl.TEXTURE_2D, 0, srgb ? gl.SRGB8_ALPHA8 : gl.RGBA8, gl.RGBA, gl.UNSIGNED_BYTE, img);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_LINEAR);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
      gl.generateMipmap(gl.TEXTURE_2D);
      owned.push(tex);
      done(tex);
    };
    // A missing asset is not an error worth shouting about: the sprite is
    // skipped and the rest of the board draws. 41 of 92 monsters have no
    // painting at all (ENGINE_PLAN §8), and no checkout is obliged to have
    // baked, so this is an expected path rather than a failure.
    img.onerror = () => done(null);
    img.src = url;
  }

  /** A draft becomes a Material the moment it has an albedo. Never before. */
  function publish(id: string): void {
    const d = drafts.get(id);
    if (disposed || !d || !d.albedo) return;
    materials.set(id, { id, albedo: d.albedo, normal: d.normal, ...d.extra });
  }

  /**
   * Ask for a painted asset and everything baked off it.
   *
   * Up to three fetches, and the ORDER OF PREFERENCE for the albedo is the
   * point: `<name>_albedo.png` first, the original second. The baked cut is the
   * source art wearing a repaired alpha — the pipeline re-keys the mattes that
   * were luminance-keyed out of an opaque render, and mean fully-opaque across
   * the set went from 59.6% to 91.6%. Without it the pieces are ghosts: a
   * figure drawn at two thirds alpha is two thirds of a figure and one third of
   * whatever is behind it, which on a dark board reads as translucency.
   */
  function request(id: string, url: string, extra: Partial<Material> = {}): void {
    if (disposed || materials.has(id) || drafts.has(id)) return;
    const baked = bakedRef(url);
    const draft = {
      extra: baked ? { normalStrength: baked.bevel ? PIECE_RELIEF : TILE_RELIEF, ...extra } : extra,
      albedo: null as WebGLTexture | null,
      normal: null as WebGLTexture | null,
    };
    drafts.set(id, draft);

    const takeAlbedo = (tex: WebGLTexture | null) => {
      draft.albedo = tex;
      publish(id);
    };
    if (baked && baked.bevel) {
      loadImage(`${BAKED_ROOT}/${baked.set}/${baked.name}_albedo.png`, true, (tex) => {
        if (tex) return takeAlbedo(tex);
        // `disposed` is checked BEFORE falling back, not only inside the load.
        // React StrictMode builds a library, throws it away and builds another;
        // without this the dead one answers its own baked load with "null,
        // because I am disposed" and then goes and fetches the original as if
        // that were a missing bake. Harmless, and it put a phantom request for
        // every ghostly original in the network log — which is exactly the
        // evidence someone would use to decide this feature was not working.
        if (disposed) return;
        loadImage(url, true, takeAlbedo);
      });
    } else {
      loadImage(url, true, takeAlbedo);
    }

    // THE CARVED RELIEF (ENGINE_PLAN §15). EDT beveling derives a height field
    // from the sprite's ALPHA, so the outline becomes the geometry and the
    // figure lights as a bas-relief instead of as a flat card. Null is flat,
    // and flat is exactly the board that shipped before this line existed.
    if (baked) {
      loadImage(`${BAKED_ROOT}/${baked.set}/${baked.name}_normal.png`, false, (tex) => {
        draft.normal = tex;
        publish(id);
      });
    }
  }

  const tiles = TILE_TEXTURES[gateId];
  if (tiles) {
    // `inlay` is what stops the floor reading as one continuous slab of rock:
    // every whole-tile boundary gets a seam and a chamfer, so the board
    // resolves into laid pieces the moment the lantern moves (§15.1).
    request(MAT_GROUND, tiles.ground, { inlay: 1 });
    request(MAT_WALL, tiles.wall, { inlay: 0.85 });
  }
  if (SPRITE_ART.player) request(MAT_HERO, SPRITE_ART.player);
  if (SPRITE_ART.merchant) request('sprite:merchant', SPRITE_ART.merchant);
  if (SPRITE_ART.tamer) request('sprite:tamer', SPRITE_ART.tamer);
  for (const icon of ['door', 'stairs', 'boss', 'barrel', 'chest', 'shrine', 'event', 'secret']) {
    const url = ICON_ART[icon];
    if (url) request(iconTextureId(icon), url);
  }

  return {
    materials,
    request,
    ready: true,
    dispose() {
      if (disposed) return;
      disposed = true;
      for (const tex of owned) gl.deleteTexture(tex);
      owned.length = 0;
      materials.clear();
      drafts.clear();
    },
  };
}

/** Ask for whatever painted figures this floor's units need. */
export function requestUnitArt(lib: MaterialLibrary, speciesIds: readonly string[]): void {
  for (const id of speciesIds) {
    const url = PAINTED_MONSTERS[id];
    if (url) lib.request(`monster:${id}`, url);
  }
}
